name: Generate and Encrypt Manifest
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Manifest
        run: ./generate_manifest.sh

      - name: Encrypt Manifest
        env:
          MANIFEST_TOKEN: ${{ secrets.MANIFEST_TOKEN }}
        run: |
          echo $MANIFEST_TOKEN | gpg --symmetric --cipher-algo AES256 --batch --yes --passphrase-fd 0 --output secret-manifest.gpg manifest.txt
