name: Encrypt Secret Manifest
on:
  push:
    branches:
      - main

jobs:
  encrypt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SOPS
        run: |
          curl -LO https://github.com/mozilla/sops/releases/download/v3.7.3/sops_3.7.3_amd64.deb
          sudo dpkg -i sops_3.7.3_amd64.deb

      - name: Generate Secret Manifest
        env:
          TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
        run: |
          echo "apiVersion: v1" > secret.yaml
          echo "data:" >> secret.yaml
          echo "  token: $(echo -n $TELE_TOKEN | base64)" >> secret.yaml

      - name: Set KMS Path
        run: |
          export KMS_PATH="projects/tf-git/locations/global/keyRings/sops-demo/cryptoKeys/my-encryption-key"

      - name: Encrypt Secret Manifest
        run: |
          sops --encrypt --encrypted-regex '^(data)$' --gcp-kms $KMS_PATH secret.yaml --output secret.enc.yaml

      - name: Set Encrypted Manifest Output
        id: set-output
        run: |
          echo "::set-output name=encrypted_manifest::$(cat secret.enc.yaml)"

      - name: Create Secret
        run: |
          echo "::set-secret name=TELE_TOKEN::${{ secrets.TELE_TOKEN }}"
