name: Encrypt Secrets

on:
  push:
    branches:
      - main

jobs:
  encrypt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate secret manifest
        run: echo "SECRET_VALUE=secret" > secret_manifest.txt

      - name: Set up sops
        uses: mozilla/sops-action@v4

      - name: Encrypt secret manifest
        run: |
          sops --encrypt --in-place secret_manifest.txt
        env:
          SOPS_PGP_FP: ${{ secrets.SOPS_PGP_FP }}

      - name: Store encrypted secret manifest
        run: |
          # Збереження зашифрованого секретного маніфесту у файлі
          cp secret_manifest.txt encrypted_secret_manifest.txt

      - name: Upload encrypted secret manifest
        uses: actions/upload-artifact@v2
        with:
          name: encrypted-secret-manifest
          path: encrypted_secret_manifest.txt

      - name: Store TELE_TOKEN in GitHub Secrets
        run: |
          echo $TELE_TOKEN >> $GITHUB_ENV
        env:
          TELE_TOKEN: ${{ secrets.TELE_TOKEN }}
